---

- name: miniconda installer is downloaded
  get_url:
    url="https://repo.continuum.io/miniconda/{{ miniconda_installer }}"
    dest="/tmp/{{ miniconda_installer }}"
    checksum="{{ miniconda_installer_checksum }}"
    force={{ 'yes' if miniconda_installer_checksum == '' else 'no' }}
    mode=0755

- name: directory {{ miniconda_prefix | dirname }} exists
  file:
    path="{{ miniconda_prefix | dirname }}"
    state=directory
    follow=yes

- name: tar is installed
  package:
    name=tar
    state=present

- name: bzip2 is installed
  package:
    name=bzip2
    state=present

- name: miniconda is installed
  command:
    '/bin/bash "/tmp/{{ miniconda_installer}}" -b -p "{{ miniconda_prefix }}"'
  args:
    creates: "{{ miniconda_prefix }}"

- name: miniconda is up-to-date
  command: '"{{ miniconda_prefix }}/bin/conda" update conda -y -q'
  register: miniconda_update
  when: miniconda_update_conda
  changed_when: '"All requested packages already installed" in miniconda_update'

- name: conda environment file /tmp/{{ miniconda_env.name }}-environment.yml is created
  copy:
    content="{{ miniconda_env | to_yaml(default_flow_style=False) }}"
    dest="/tmp/{{ miniconda_env.name }}-environment.yml"
  when: miniconda_env != ''

- include: environment.yml
  when: miniconda_env != ''
